version: "3.6"

services:
  mongodb:
    image: mongo:4
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "12345678"
      MONGO_INITDB_DATABASE: "test"
    ports:
      - 27021:27017
